### ISSUE TITLE
JOSS review: installation instructions

### ISSUE THREAD

**Issue by mefuller** [cartemic/pypbomb#7]

**Comment by mefuller** [comment]
Please update and verify installation instructions to link to homepages for dependencies to provide alternate installation methods (e.g. cantera and pint both available with pip, some system package managers)

**Comment by cartemic** [comment]
Oh neat, cantera is on pip now! That should simplify things a lot.

**Comment by cartemic** [comment]
This may take some time. The new version of cantera doesn't seem to work with my code.

**Comment by cartemic** [comment]
- [x] Change installer to pip only
- [ ] Adjust code for new version of Cantera
- [ ] Adjust CI to use new installation process
- [ ] Unify CI and install dependencies to single file
- [ ] Update documentation

**Comment by cartemic** [comment]
@mefuller I've added a PR that I hope will resolve this issue. If you'd like, I would be happy to add you as a contributor if you would like to approve the PR. Otherwise I will hold off on merging it to master until you're happy with the changes. The [updated documentation](https://cartemic.github.io/pypbomb/installation.html) is currently live. Please let me know what you think!
